openapi: 3.0.3
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST GnuCash

servers:
  - url: "/api"

# Paths supported by the server application
paths:
  /transactions:
    post:
      operationId: "models.transactions.new"
      tags:
        - "Transactions"
      requestBody:
        description: "Insert a new transaction"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTransaction'
      responses:
        201:
          description: Created
          content:
            text/plain:
              schema:
                description: "Transaction guid"
                type: string
                example: "3421a33ca15343d08076b2ee5f6e73c9"
  /transactions/find_asset:
    get:
      operationId: "models.transactions.find_asset"
      tags:
        - "Transactions"
      parameters:
        - name: "description"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "account"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        200:
          description: "Asset transactions find operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Transaction'
  /transactions/find_expense:
    get:
      operationId: "models.transactions.find_expense"
      tags:
        - "Transactions"
      parameters:
        - name: "description"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "account"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        200:
          description: "Expense transactions find operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Transaction'
  /transactions/find_income:
    get:
      operationId: "models.transactions.find_income"
      tags:
        - "Transactions"
      parameters:
        - name: "description"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "account"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        200:
          description: "Income transactions find operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Transaction'
components:
  schemas:
    Transaction:
      type: object
      properties:
        guid:
          type: "string"
        description:
          type: "string"
        date:
          type: "string"
        amount:
          type: "number"
        account_name:
          type: "string"
        account_type:
          type: "string"
    NewTransaction:
      type: object
      required:
        - from_account
        - to_account
        - description
        - amount
      properties:
        from_account:
          type: "string"
        to_account:
          type: "string"
        description:
          type: "string"
        amount:
          type: "number"
        date:
          type: "string"
