openapi: 3.0.2
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article

servers:
  - url: "/api"

# Paths supported by the server application
paths:
#  /transactions:
#    get:
#      operationId: "models.transactions.read_all"
#      tags:
#        - "Transactions"
#      responses:
#        200:
#          description: "Transactions list operation"
#          content:
#            application/json:
#              schema:
#                type: "array"
#                items:
#                  properties:
#                    guid:
#                      type: "string"
#                    enter_date:
#                      type: "string"
#                    description:
#                      type: "string"
  /transactions/find:
    get:
      operationId: "models.transactions.find"
      tags:
        - "Transactions"
      parameters:
        - name: "description"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "account"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        200:
          description: "Transactions find operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  properties:
                    guid:
                      type: "string"
                    enter_date:
                      type: "string"
                    description:
                      type: "string"
